import React from "react";
import {
  ShieldAlert,
  Wind,
  CloudRain,
  Waves,
  Activity,
  Building2,
  Users,
  Database,
  Sparkles,
  AlertTriangle,
  Info,
  Cpu
} from "lucide-react";

/**
 * Returns icon corresponding to factor id
 */
function getFactorIcon(id) {
  switch (id) {
    case "wind":
      return <Wind size={16} className="text-orange-600" />;
    case "rain":
      return <CloudRain size={16} className="text-blue-600" />;
    case "surge":
      return <Waves size={16} className="text-cyan-700" />;
    case "inundation":
      return <Activity size={16} className="text-red-600" />;
    case "infrastructure":
      return <Building2 size={16} className="text-purple-600" />;
    case "exposure":
      return <Users size={16} className="text-emerald-700" />;
    default:
      return <AlertTriangle size={16} className="text-slate-600" />;
  }
}

/**
 * Classification badge styling helper
 */
function renderClassificationBadge(classification, label) {
  let badgeClass = "badge-prov-derived";
  let title = "Derived from multi-model ensembles or geospatial calculations";

  if (classification === "OBSERVED") {
    badgeClass = "badge-prov-observed";
    title = "Empirically measured by field sensors or official registry";
  } else if (classification === "SIMULATED") {
    badgeClass = "badge-prov-simulated";
    title = "Generated by hydrodynamic or surge numerical model";
  }

  return (
    <span
      className={`evidence-classification-pill ${badgeClass}`}
      title={title}
    >
      <span className="pill-dot"></span>
      {label || classification}
    </span>
  );
}

/**
 * Government-Grade Evidence & Factor Decomposition Panel
 *
 * Answers with zero ambiguity:
 * 1. WHAT is current risk?
 * 2. WHY is risk high?
 * 3. WHICH hazard/exposure factors contribute?
 * 4. WHAT evidence supports those factors?
 * 5. HOW is evidence classified (OBSERVED, DERIVED, SIMULATED)?
 */
export default function EvidencePanel({
  evidence,
  onNavigateTab
}) {
  if (!evidence) {
    return (
      <div className="evidence-panel-empty">
        <Database size={24} className="text-slate-400 mb-2" />
        <div className="text-sm font-semibold text-slate-700">NO DISTRICT SELECTED</div>
        <div className="text-xs text-slate-500">Select a district from the matrix or map to inspect evidence factors.</div>
      </div>
    );
  }

  const {
    districtName,
    state,
    authoritativeRisk,
    primaryDrivers = [],
    factors = [],
    cycloneContext,
    provenance
  } = evidence;

  return (
    <div className="evidence-deepdive-panel">
      {/* 1. Header: Authoritative Risk Score & Integrity Statement */}
      <div className="evidence-header-card">
        <div className="evidence-header-top">
          <div>
            <div className="flex items-center gap-2">
              <span className="evidence-district-title font-bold text-slate-900 text-lg">
                {districtName}
              </span>
              <span className="text-xs font-semibold text-slate-500 bg-slate-100 px-2 py-0.5 rounded border border-slate-200">
                {state} STATE
              </span>
              <span className="text-xs font-mono text-slate-500">
                Coastline: {evidence.coastalLineKm} km
              </span>
            </div>
            <div className="text-xs text-slate-500 font-mono mt-0.5">
              TIMESTEP: [{provenance.stepId}] • SCENARIO: {provenance.scenarioName}
            </div>
          </div>

          {/* Authoritative Risk Badge (Exact match to backend score) */}
          <div className="evidence-score-badge-wrap">
            <div className="evidence-score-sublabel text-right font-mono text-slate-500 text-xs">
              AUTHORITATIVE RISK
            </div>
            <div className="flex items-center gap-2">
              <span
                className="evidence-score-number font-mono font-black text-2xl"
                style={{ color: authoritativeRisk.color }}
              >
                {authoritativeRisk.score}<span className="text-sm font-normal text-slate-500">/100</span>
              </span>
              <span
                className="evidence-band-pill font-mono font-bold text-xs px-2.5 py-1 rounded text-white"
                style={{ backgroundColor: authoritativeRisk.color }}
              >
                {authoritativeRisk.band}
              </span>
            </div>
          </div>
        </div>

        {/* Deterministic Rule Engine Integrity Banner */}
        <div className="engine-integrity-banner">
          <div className="flex items-start gap-2">
            <Cpu size={14} className="text-indigo-600 mt-0.5 flex-shrink-0" />
            <div className="text-xs text-indigo-950 font-medium">
              <strong>Deterministic Integrity Guarantee:</strong> {authoritativeRisk.ruleEngineStatement}
            </div>
          </div>
        </div>

        {/* Operational Provenance Tag */}
        <div className="operational-scenario-tag">
          <span className="provenance-pulse-icon"></span>
          <span>{authoritativeRisk.operationalProvenance}</span>
        </div>
      </div>

      {/* 2. Primary Vulnerability Drivers (WHY is risk high?) */}
      <div className="evidence-section-block">
        <div className="evidence-section-header">
          <div className="flex items-center gap-1.5">
            <ShieldAlert size={14} className="text-orange-600" />
            <h3 className="evidence-section-title">PRIMARY VULNERABILITY DRIVERS</h3>
          </div>
          <span className="text-xs font-mono text-slate-500">SORTED BY THREAT INTENSITY</span>
        </div>

        <div className="drivers-cards-grid">
          {primaryDrivers.length === 0 ? (
            <div className="p-3 text-xs text-slate-500 font-mono bg-slate-50 rounded border border-slate-200">
              No critical vulnerability drivers triggered for this timestep.
            </div>
          ) : (
            primaryDrivers.map((driver) => (
              <div
                key={driver.rank}
                className={`primary-driver-card driver-${driver.severity.toLowerCase()}`}
              >
                <div className="driver-rank-chip font-mono">{driver.rank}</div>
                <div className="driver-content-wrap">
                  <div className="driver-title font-semibold text-slate-900 text-xs">
                    {driver.fullText}
                  </div>
                  <div className="driver-meta font-mono text-[10px] text-slate-500 mt-1 flex items-center gap-2">
                    <span className="driver-severity-tag">SEVERITY: {driver.severity}</span>
                    <span>•</span>
                    <span>SOURCE: OSDMA-NDMA MULTI-HAZARD MATRIX</span>
                  </div>
                </div>
              </div>
            ))
          )}
        </div>
      </div>

      {/* 3. Hazard & Exposure Factor Decomposition (WHICH factors contribute & WHAT evidence supports them?) */}
      <div className="evidence-section-block">
        <div className="evidence-section-header">
          <div className="flex items-center gap-1.5">
            <Activity size={14} className="text-blue-600" />
            <h3 className="evidence-section-title">HAZARD & EXPOSURE FACTOR DECOMPOSITION</h3>
          </div>
          <span className="text-xs font-mono text-slate-500">6-DIMENSIONAL PARAMETER SUITE</span>
        </div>

        <div className="factors-decomposition-grid">
          {factors.map((factor) => (
            <div key={factor.id} className="factor-evidence-card">
              {/* Factor Header */}
              <div className="factor-card-header">
                <div className="flex items-center gap-2">
                  <div className="factor-icon-wrap">
                    {getFactorIcon(factor.id)}
                  </div>
                  <div>
                    <span className="factor-name-label font-bold text-slate-800 text-xs">
                      {factor.factorName}
                    </span>
                    <div className="factor-sublabel font-mono text-[10px] text-slate-500">
                      {factor.shortLabel}
                    </div>
                  </div>
                </div>
                {renderClassificationBadge(factor.classification, factor.classificationLabel)}
              </div>

              {/* Factor Value & Status */}
              <div className="factor-value-row">
                <div className="factor-main-metric font-mono font-bold text-slate-900 text-xl">
                  {factor.value} <span className="text-xs font-normal text-slate-600">{factor.unit}</span>
                </div>
                <div className={`factor-status-pill status-${factor.severity.toLowerCase()}`}>
                  {factor.severityLabel}
                </div>
              </div>

              {/* Sub-value / Context Note */}
              <div className="factor-subvalue-text text-xs text-slate-700 font-medium">
                {factor.subvalue}
              </div>

              {/* Threshold Comparison */}
              <div className="factor-threshold-row">
                <Info size={11} className="text-slate-400 mt-0.5 flex-shrink-0" />
                <span className="font-mono text-[11px] text-slate-600">
                  {factor.threshold}
                </span>
              </div>

              {/* Operational & Sensor Source Citation */}
              <div className="factor-source-footer">
                <div className="source-label-row font-mono text-[10px] text-slate-500">
                  <span className="font-bold text-slate-700">PROVENANCE:</span> {factor.source}
                </div>
                <div className="factor-op-note text-[11px] text-slate-600 mt-1">
                  {factor.operationalNote}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* 4. Evidence Classification & Provenance Audit Ledger */}
      <div className="evidence-audit-ledger">
        <div className="audit-ledger-header">
          <div className="flex items-center gap-1.5">
            <Database size={13} className="text-slate-700" />
            <span className="font-bold text-xs text-slate-800 font-mono">EVIDENCE CLASSIFICATION AUDIT LEDGER</span>
          </div>
          <span className="font-mono text-[10px] text-slate-500">
            TOTAL EVIDENCE FACTORS: {provenance.totalCount}
          </span>
        </div>

        <div className="audit-chips-row">
          <div className="audit-chip">
            <span className="pill-dot bg-emerald-600"></span>
            <span className="chip-label font-mono text-xs">OBSERVED FACTORS:</span>
            <strong className="chip-count font-mono text-emerald-800">{provenance.observedCount}</strong>
            <span className="chip-desc text-[10px] text-slate-500">(AWS & SDMA Registry)</span>
          </div>

          <div className="audit-chip">
            <span className="pill-dot bg-blue-600"></span>
            <span className="chip-label font-mono text-xs">DERIVED FACTORS:</span>
            <strong className="chip-count font-mono text-blue-800">{provenance.derivedCount}</strong>
            <span className="chip-desc text-[10px] text-slate-500">(Ensemble WRF & Hydro 2D)</span>
          </div>

          <div className="audit-chip">
            <span className="pill-dot bg-purple-600"></span>
            <span className="chip-label font-mono text-xs">SIMULATED FACTORS:</span>
            <strong className="chip-count font-mono text-purple-800">{provenance.simulatedCount}</strong>
            <span className="chip-desc text-[10px] text-slate-500">(INCOIS SS-EWS Model)</span>
          </div>
        </div>

        {/* Cyclone Eye Telemetry Reference */}
        {cycloneContext && (
          <div className="cyclone-telemetry-ref-bar font-mono text-[11px] text-slate-600 mt-2 p-2 bg-slate-50 border border-slate-200 rounded">
            <strong>STORM CENTER TELEMETRY:</strong> {cycloneContext.category} at {cycloneContext.position} • Central Pressure: {cycloneContext.pressureMb} hPa • Wind Radii: R34={cycloneContext.windRadii.r34Km}km, R50={cycloneContext.windRadii.r50Km}km, R64={cycloneContext.windRadii.r64Km}km
          </div>
        )}
      </div>

      {/* 5. Strategic AI Advisory Synthesis Quick Action */}
      {onNavigateTab && (
        <div className="evidence-advisory-action-card">
          <div className="flex items-center justify-between gap-4 flex-wrap">
            <div>
              <div className="flex items-center gap-1.5 font-bold text-slate-900 text-xs">
                <Sparkles size={14} className="text-indigo-600" />
                <span>GENERATE STRATEGIC OPERATIONAL ADVISORY</span>
              </div>
              <div className="text-xs text-slate-600 mt-0.5">
                Pass this verified evidence package into Gemini AI for strategic executive summary and NDRF deployment recommendations.
              </div>
            </div>

            <button
              type="button"
              className="btn-synthesize-evidence-advisory"
              onClick={() => onNavigateTab("advisories")}
            >
              <Sparkles size={14} />
              <span>SYNTHESIZE ADVISORY FOR {districtName.toUpperCase()}</span>
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
